.TH GENUP-LITE 8 "Version 1.0.1: January 2015"
.SH NAME
genup-lite \- update Portage tree, and all installed packages
.SH SYNOPSIS
.B genup-lite
[\fIoptions\fR]
.SH DESCRIPTION
.B genup-lite
is a utility intended to simplify the process of keeping your Gentoo system
up to date. 
When invoked, it automatically performs the following steps, in order:
.br
.RS
.IP \(bu 2
updates Portage tree (and active overlays), and syncs \fBeix\fR(1)
.br
(using \fBeix-sync\fR)
.IP \(bu 2
removes any prior \fBemerge\fR(1) resume history;
.br
(using \fBemaint --fix cleanresume\fR)
.IP \(bu 2
ensures Portage itself is up-to-date
.br
(using \fBemerge --oneshot --update portage\fR)
.IP \(bu 2
updates all packages in the @world set
.br
(using \fBemerge --deep --with-bdeps=y --newuse --update @world\fR)
.IP \(bu 2
builds any external modules (such as those for VirtualBox)
.br
(using \fBemerge @module-rebuild\fR)
.IP \(bu 2
rebuilds any packages depending on stale libraries
.br
(using \fBemerge @preserved-rebuild\fR)
.IP \(bu 2
updates any old \fBperl\fR(1) modules (if desired)
.br
(using \fBperl-cleaner --all\fR)
.IP \(bu 2
updates any old \fBpython\fR(1) modules (if desired)
.br
(using \fBpython-updater\fR)
.IP \(bu 2
resolves clashing config file changes (in interactive mode)
.br
(using \fBdispatch-conf\fR)
.IP \(bu 2
removes unreferenced packages
.br
(using \fBemerge --depclean\fR)
.IP \(bu 2
fixes missing shared library dependencies
.br
(using \fBrevdep-rebuild\fR)
.IP \(bu 2
rebuilds any packages depending on stale libraries (again)
.br
(using \fBemerge @preserved-rebuild\fR)
.IP \(bu 2
removes any unused source tarballs (if desired)
.br
(using \fBeclean --deep distfiles\fR)
.IP \(bu 2
updates environment settings (as a precautionary measure)
.br
(using \fBenv-update\fR)
.PP
.RE
The \fBgenup-lite\fR utility can be invoked in non-interative (default) or 
interactive mode (see the \fB--ask\fR option, below).
Non-interactive mode is suitable for use in a scripted invocation, for example
as part of a nightly \fBcron\fR(8) job (see \fBAUTOMATING GENUP-LITE\fR, below).

Note that \fBgenup-lite\fR does not attempt to upgrade the kernel (this is what
makes it 'lite', comprared to the full \fBgenup\fR(8) utility) - so it is suitable
for use in an embedded environment.
.SH OPTIONS
.TP
.BR \-a ", " \-\-ask
By default, \fBgenup-lite\fR will:
a) attempt to perform the update automatically;
b) fail immediately on any error; 
c) invoke underlying tools in non-interactive mode; and
d) not invoke \fBdispatch-conf\fR(1) to resolve clashing configuration file
updates (unless the \fB--dispatch-conf\fR option has been specified).

However, if you supply the \fB--ask\fR option, then \fBgenup-lite\fR will instead:
a) prompt for confirmation during important steps of the update;
b) fail immediately on any error, \fBexcept\fR when that error occurs during the
@world update \fBemerge\fR(1) (in which case, prompt whether or not to retry,
allowing the problem \(em for example, a missing use flag \(em to be fixed in
a separate terminal);
c) invoke most underlying tools in interactive mode; and
d) invoke \fBdispatch-conf\fR(1) to resolve clashing configuration file updates.

.TP
.BR \-c ", " \-\-dispatch\-conf
Always forces \fBdispatch-conf\fR(1) to be run, where necessary, even if
not in interactive mode.
.TP
.BR \-e ", " \-\-emerge\-args\=ADDITIONAL_ARGS
Passes the specified arguments to the main
.BR emerge (1)
invocation. One possible use here is to specify:
.br
\fB--emerge-args="--autounmask-write"\fR

This instructs \fBemerge\fR(1) to automatically make any necessary changes to 
Portage configuration files to ensure that the process can proceed (adding
additional use flags, allowing libraries, and so on), provided the Portage
\fB--autounmask\fR option is enabled (which by default it is).
This can be useful when
running \fBgenup-lite\fR in an unattended situation (assuming of course you are
comfortable with such changes being made automatically on your behalf).
.TP
.BR \-h ", " \-\-help
Displays a short help screen, and exits.
.TP
.BR \-k ", " \-\-keep\-old\-distfiles
By default, \fBgenup-lite\fR will remove any source tarballs that have previously
been downloaded by Portage, but which do not relate to the installed version of
any package. This option inhibits such cleaning.
.TP
.BR \-p ", " \-\-no\-perl\-cleaner
Do not attempt to run \fBperl-cleaner\fR(1) during the process.
.TP
.BR \-P ", " \-\-no\-python\-updater
Do not attempt to run \fBpython-updater\fR(1) during the process.
.TP
.BR \-v ", " \-\-verbose
Provides more verbose output from invoked tools, where possible.
.TP
.BR \-V ", " \-\-version
Displays the version number of \fBgenup-lite\fR, and exits.
.SH EXIT STATUS
The exit status is 0 if the update completed successfully, and 1 otherwise.
.SH PARALLEL MAKE
Quite frequently, large \fBemerge\fR(1) runs fail because one
or more of the invoked ebuilds have problems running with parallel
\fBmake\fR(1) (as set via MAKEOPTS="-jN", where N>1).

Because of this, \fBgenup-lite\fR will attempt to
automatically resume any \fBemerge\fR(1) operation with parallel make
inhibited, should the original operation fail. A warning is issued if this
happens.

In a similar fashion, if you are using distributed compilation
with the \fBdistcc\fR and \fBdistcc-pump\fR features, these will be
automatically inhibited if operations are retried.
.SH AUTOMATING GENUP-LITE
Should you wish to run \fBgenup-lite\fR automatically, you need to ensure it has
an appropriate environment.
For example, you could put the following script in
\fI/etc/cron.daily/genup-lite\fR, to execute an update nightly (be sure to make
the file executable):
.nf
.RS

#!/bin/bash
export PATH="/usr/local/sbin:/usr/local/bin:"\\
"/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
genup-lite >/var/log/latest-genup-lite-run.log 2>&1
.fi
.SH COPYRIGHT
.nf
Copyright \(co 2015 sakaki
License GPLv3+ (GNU GPL version 3 or later)
<http://gnu.org/licenses/gpl.html>

This is free software, you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.fi
.SH AUTHORS
sakaki \(em send bug reports or comments to <sakaki@deciban.com>
.SH "SEE ALSO"
.BR dispatch-conf (1),
.BR eclean (1),
.BR emerge (1),
.BR eix (1),
.BR emaint (1),
.BR make (1),
.BR perl-cleaner (1),
.BR python-updater (1),
.BR buildkernel (8),
.BR revdep-rebuild (1),
.BR cron (8),
.BR genup (8),
.BR portage (5).
